### ISSUE TITLE
Python error when the service return http error 204

### ISSUE THREAD

**Issue by MarioLocati** [INGV/qquake#73]
When a fdsn (event, macroseismic o station) service returns an https error code 204 "no content", qquake generate a python error.

To reproduce the issue:
- select "earthquake parameters"
- select "INGV ISIDe"
- enter 6 as the minimum magnitude
- do not enter any time coverage filter
- selecte "Italy" as the predefined geographical coverage filter
- select "basic" as the output table format

Below the stack trace of the generated by the Python error
```
IndexError: list index out of range 
Traceback (most recent call last):
  File "/home/mario/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qquake/gui/qquake_dialog.py", line 966, in _fetcher_finished
    layer = self.fetcher.create_event_layer()
  File "/home/mario/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qquake/fetcher.py", line 774, in create_event_layer
    return self.events_to_layer(self.result, self.preferred_origins_only, self.preferred_magnitudes_only)
  File "/home/mario/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qquake/fetcher.py", line 618, in events_to_layer
    vl = self._create_empty_event_layer()
  File "/home/mario/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qquake/fetcher.py", line 569, in _create_empty_event_layer
    vl.dataProvider().addAttributes(self.result.to_event_fields(self.output_fields))
  File "/home/mario/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qquake/basic_text/basic_text_parser.py", line 186, in to_event_fields
    fields.append(QgsField(self.headers[0], QVariant.String))
IndexError: list index out of range
```

See the screenshot below
![image](https://github.com/INGV/qquake/assets/20398568/48583b2f-9e3c-4961-ba2e-5d4a82cac301)

**Comment by MarioLocati** [comment]
Solved by these commits https://github.com/INGV/qquake/commit/7ebb5180ecc5bf14d77fa48c883fa6f61b0b02ea and https://github.com/INGV/qquake/commit/84c3ae2c16f8264f1cb561de65fd2b41c5d76650

Thank you @GiorgioMariaDeSantis !
